<?php

namespace Memsource\Model;

class JobFilter {

  const STATUS_ASSIGNED = 'ASSIGNED';
  const STATUS_COMPLETED = 'COMPLETED';
  const STATUS_COMPLETED_BY_LINGUIST = 'COMPLETED_BY_LINGUIST';
  const STATUS_DECLINED_BY_LINGUIST = 'DECLINED_BY_LINGUIST';
  const STATUS_EMAILED = 'EMAILED';
  const STATUS_NEW = 'NEW';
  const STATUS_PRECEDING_COMPLETED = 'PRECEDING_COMPLETED';
  const STATUS_PRECEDING_NOT_COMPLETED = 'PRECEDING_NOT_COMPLETED';
}